---
INPUT_FILE_NAME: "mock_data.csv"
OUTPUT_FILE_NAME: "mock_data_transformed.csv"
SOC_LOOKUP_FILE_NAME: "soc_2020_sample.csv"

INPUT_FILEPATH: "input/"
OUTPUT_FILEPATH: "output/"

STRING_COLUMNS:
    - "Forename"
    - "MiddleName"
    - "Surname"
COLUMN_RENAME_DICT:
    forename: "first_name"
    surname: "last_name"
SOC_LOOKUP_COLUMNS:
    df_col: "SOC"
    lookup_col: "SOC_2020"

