---
INPUT_FILE_NAME: "mock_data.csv"
OUTPUT_FILE_NAME: "mock_data_transformed.csv"

INPUT_FILEPATH: "input/"
OUTPUT_FILEPATH: "output/"

STRING_COLUMNS:
    - "Forename"
    - "MiddleName"
    - "Surname"
COLUMN_RENAME_DICT:
    forename: "first_name"
    surname: "last_name"

