repos:
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-aws-credentials
      args: [ --allow-missing-credentials ]
    - id: detect-private-key
    - id: pretty-format-json
  # Ruff hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    - id: ruff # linter
      args: [ --fix ]
    - id: ruff-format # formatter
  # Black hooks
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
  # Pytest-check hooks
  - repo: local
    hooks:
    - id: pytest-check
      name: pytest check
      entry: pytest # -v --cov=src --cov-report term-missing --cov-fail-under=80
      language: system
      pass_filenames: false
      always_run: true